import logging
import numpy as np
import torch
import cv2
from PIL import Image

logger     = logging.getLogger(__name__)
_model     = None
_processor = None
_device    = torch.device("cuda" if torch.cuda.is_available() else "cpu")

CLIP_MODEL_ID = "openai/clip-vit-large-patch14"

_FAKE_PROMPTS = [
    "a photo generated by artificial intelligence",
    "a synthetic image created by a generative model",
    "a deepfake image",
    "an AI generated artwork",
]
_REAL_PROMPTS = [
    "a real photograph taken by a camera",
    "a genuine photo of a real scene",
    "an authentic image",
    "a natural photograph",
]


def _get_model():
    global _model, _processor
    if _model is None:
        from transformers import CLIPProcessor, CLIPModel
        logger.info("[CLIP] Carregando modelo...")
        _processor = CLIPProcessor.from_pretrained(CLIP_MODEL_ID)
        _model     = CLIPModel.from_pretrained(CLIP_MODEL_ID).to(_device)
        _model.eval()
        logger.info("[CLIP] Modelo carregado.")
    return _model, _processor


def _predict_pil(image: Image.Image) -> float:
    """Retorna confidence de FAKE (0.0 a 1.0) para uma PIL Image."""
    model, processor = _get_model()

    all_prompts = _FAKE_PROMPTS + _REAL_PROMPTS
    inputs = processor(
        text=all_prompts,
        images=image,
        return_tensors="pt",
        padding=True,
    ).to(_device)

    with torch.no_grad():
        outputs = model(**inputs)
        probs   = torch.softmax(outputs.logits_per_image, dim=1)[0].cpu().numpy()

    n_fake     = len(_FAKE_PROMPTS)
    fake_score = float(np.sum(probs[:n_fake]))
    real_score = float(np.sum(probs[n_fake:]))
    total      = fake_score + real_score + 1e-9
    return round(fake_score / total, 4)


def predict_image(file_path: str) -> dict:
    image      = Image.open(file_path).convert("RGB")
    confidence = _predict_pil(image)

    fake_score = confidence
    real_score = round(1.0 - confidence, 4)

    return {
        "prediction": "FAKE" if confidence >= 0.5 else "REAL",
        "confidence": confidence,
        "method":     "clip_zero_shot",
        "version":    "1.0",
        "metadata": {
            "fake_score": fake_score,
            "real_score": real_score,
        },
    }


def predict_video(file_path: str, num_frames: int = 10) -> dict:
    cap   = cv2.VideoCapture(file_path)
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total == 0:
        cap.release()
        raise RuntimeError(f"[CLIP] Vídeo sem frames: {file_path}")

    indices       = np.linspace(0, max(total - 1, 0), num=num_frames, dtype=int)
    probs         = []
    frame_results = []

    for idx in indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(idx))
        ret, frame = cap.read()
        if not ret or frame is None:
            continue

        image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        conf  = _predict_pil(image)
        probs.append(conf)
        frame_results.append({
            "frame_index": int(idx),
            "confidence":  conf,
            "prediction":  "FAKE" if conf >= 0.5 else "REAL",
        })

    cap.release()

    if not probs:
        raise RuntimeError("[CLIP] Nenhum frame extraído do vídeo.")

    avg_conf    = round(float(np.mean(probs)), 4)
    fake_frames = sum(1 for p in probs if p >= 0.5)

    return {
        "prediction": "FAKE" if avg_conf >= 0.5 else "REAL",
        "confidence": avg_conf,
        "method":     "clip_zero_shot",
        "version":    "1.0",
        "metadata": {
            "fake_score":      avg_conf,
            "real_score":      round(1.0 - avg_conf, 4),
            "frames_analyzed": len(frame_results),
            "fake_frames":     fake_frames,
            "real_frames":     len(frame_results) - fake_frames,
            "max_confidence":  round(float(np.max(probs)), 4),
        },
        "frames": frame_results,
    }